"""empty message

Revision ID: 60500ed28d9b
Revises: 
Create Date: 2023-06-20 06:25:48.819898

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from alembic.ddl import postgresql

# revision identifiers, used by Alembic.
revision = '60500ed28d9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), autoincrement=False, nullable=False),
                    sa.Column('creation_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              autoincrement=False, nullable=True),
                    sa.Column('update_date', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.Column('created_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), autoincrement=False, nullable=True),
                    sa.Column('updated_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), autoincrement=False, nullable=True),
                    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('mobile', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(), nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('email', name='user_email_key'),
                    sa.UniqueConstraint('mobile', name='user_mobile_key')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
